"""Resume_screener.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nL6qG8TtKvwh29yIG3QgtQr1F-swMwxM
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

df = pd.read_excel('/content/combined_dataset_with_embeddings.xlsx')

df.head()

vectorizer = TfidfVectorizer()
vectorizer.fit(df['Job Description'] + df['Resume'])

job_description_vectors = vectorizer.transform(df['Job Description'])
resume_vectors = vectorizer.transform(df['Resume'])

similarity_scores = cosine_similarity(job_description_vectors, resume_vectors)
df['similarity_scores'] = similarity_scores.diagonal()

role_similarity = df.groupby('Role')['similarity_scores'].mean()
print("Average Similarity Scores by Role:\n")
role_similarity

threshold = 0.5  
df['Decision'] = df['similarity_scores'].apply(lambda score: 'Selected' if score >= threshold else 'Rejected')

bins = [0, 0.1, 0.2, 0.4, 0.6, 0.8, 1]
labels = ['0-0.1', '0.1-0.2', '0.2-0.4', '0.4-0.6', '0.6-0.8', '0.8-1']
df['similarity_bin'] = pd.cut(df['Resume_JobDescription_Score'], bins=bins, labels=labels, include_lowest=True)
distribution = df.groupby(['similarity_bin', 'Decision', 'Role']).size().unstack(fill_value=0)

distribution